export const DEVELOPMENT = "development";
export const GET_MODEL_CELSIUSTOFAHRENHEIT = "GET_MODEL_CELCIUSTOFAHRENHEIT";
export const GET_MODEL_RECOGNIZE_NUMBER = "GET_MODEL_RECOGNIZE_NUMBER";
export const GET_MODEL_RECOGNIZE_CAT_OR_DOG = "GET_MODEL_RECOGNIZE_CAT_OR_DOG";